mittwald/cli

README.md
src/commands/app/install/contao.tsx
src/commands/app/install/joomla.tsx
src/commands/app/install/matomo.tsx
src/commands/app/install/node.tsx
src/commands/app/install/php.tsx
src/commands/app/install/shopware5.tsx
src/commands/app/install/shopware6.tsx
src/commands/app/install/typo3.tsx
src/commands/app/install/wordpress.tsx
src/lib/app/Installer.tsx
src/lib/app/flags.tsx
src/lib/array_types.ts

- Add AppInstaller class to deduplicate installation commands
- Remove TODO
- Clean up stuff

Deduplicate code in app installer commands

---

src/commands/app/install/php.tsx

Fix PHP app installation

---

src/rendering/react/ExecRenderBaseCommand.tsx

Allow "render" function in exec commands to return simple strings

---

README.md
src/commands/mail/address/create.tsx

Add option to create forwarding email address

---

.devcontainer/devcontainer.json
.vscode/launch.json
.vscode/tasks.json
CONTRIBUTING.md
README.md

- Refer to contributing guide in README
- Explain development environment
- Add devcontainer configuration
- Add VS code tasks
- Mention devcontainer in contribution doc

Improve contributor experience

---

src/lib/project/flags.ts

Add options to use UUIDs for subordinate resources without relying on the parent ID

---

README.md
src/ExtendedBaseCommand.tsx
src/commands/app/download.tsx
src/commands/app/ssh.ts
src/commands/context/set.ts
src/lib/app/flags.tsx
src/lib/app/ssh.ts
src/lib/context.ts
src/lib/hasbin.ts
src/lib/project/flags.ts
src/rendering/process/components/ProcessState.tsx
src/rendering/process/process.tsx
src/rendering/react/RenderBaseCommand.tsx

This PR adds a `app download` command that rsync's an app installation's entire installation directory to a local path.

Add "app download" command

---

README.md
src/commands/sftp-user/delete.ts
src/commands/ssh-user/delete.ts

- Add "ssh-user delete" command
- Also add "sftp-user delete" command

Add "{sftp|ssh}-user delete" commands

---

.github/dependabot.yml

Increase dependabot PR limit and interval

---

.github/dependabot.yml

- **ci: make sure @mittwald/api-* packages are updated together**
- **ci: fix typo**

Fix typo in dependabot configuration

---

yarn.lock

directly after doing a clean checkout on `master` and running `yarn install` there are changes in the `yarn.lock` file …

Fix @oclif/core in yarn.lock

---

README.md
src/commands/app/install/nextcloud.tsx

Fix incorrect app label for Nextcloud

---

README.md
src/commands/ddev/init.tsx
src/commands/ddev/render-config.ts
src/lib/ddev/config_builder.ts
src/lib/ddev/flags.ts
src/lib/error/InteractiveInputRequiredError.ts
src/rendering/process/components/InteractiveInputDisabled.tsx
src/rendering/process/components/ProcessInput.tsx
src/rendering/process/components/ProcessSelect.tsx
src/rendering/process/components/ProcessSelectStateSummary.tsx
src/rendering/process/components/ProcessStateIcon.tsx
src/rendering/process/components/ProcessStateSummary.tsx
src/rendering/process/process.tsx
src/rendering/process/process_fancy.tsx
src/rendering/process/process_quiet.ts
src/rendering/react/components/ErrorBox.tsx

Add option to specify database on "ddev init" command

---

src/BaseCommand.ts
src/commands/ddev/init.tsx
src/commands/login/reset.tsx
src/commands/login/token.ts
src/lib/auth/token.ts
src/lib/ddev/config_builder.ts
src/lib/ddev/flags.ts
src/lib/ddev/init_assert.tsx
src/lib/ddev/init_database.tsx

Relates to #305 
Depends on the following PRs being merged, first:
- #307

Initialize mittwald API token on `ddev init`

---

docs/sftp-user.md
docs/ssh-user.md
src/commands/sftp-user/update.tsx
src/commands/ssh-user/update.tsx

just a little fix for a little mix-up

fix mixed up flag descriptions

---

package.json

Set correct S3 host for package upload

---

src/lib/resources/app/sync.ts

Follow-Up for a bug introduced in #744

Fix wrongly evaluated flag name in "app upload|download"

---

docs/database.md
src/commands/database/mysql/dump.tsx
src/commands/database/mysql/list.ts
src/commands/database/mysql/port-forward.tsx
src/lib/resources/database/mysql/connect.ts
src/lib/resources/database/mysql/flags.ts
src/lib/resources/database/mysql/temp_user.ts

fix: specify charset when dumping MySQL database

---

README.md
docs/container.md
package.json

fix: add missing topic descriptions to package.json

---

src/lib/basecommands/BaseCommand.ts
src/lib/error/NoTokenFoundError.ts
src/rendering/react/components/ErrorBox.tsx

This PR improves the UX a bit when the user is not logged in yet, and no token is present.
Fixes #1135

feat: improve UX when user is not authenticated

---

docs/container.md
src/commands/container/run.tsx

fix: update "container run" to use --publish flag and remove shorthand -p due to conflict with --project flag

---

package.json
src/hooks/prerun/update-brew-check.ts

relates https://github.com/mittwald/cli/issues/1322

Add prerun hook for update: Check if installed with brew
